Models/EventVendor.cs
using System;
using System.Collections.Generic;

namespace Food_Scape.Models;

public partial class EventVendor
{
    public int EventVendorId { get; set; }

    public int? EventId { get; set; }

    public int? VendorId { get; set; }

    public virtual Event? Event { get; set; }

    public virtual Vendor? Vendor { get; set; }
}

Controllers/EventVendorController.cs
using Food_Scape.Models;
using Food_Scape.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Food_Scape.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EventVendorController : Controller
    {
        FoodScapeContext _foodScapeContext;

        public EventVendorController(FoodScapeContext foodScapeContext)
        {
            _foodScapeContext = foodScapeContext;
        }

        /// <summary>
        /// EventVendor Admin Pages / CRUD
        /// 
        /// The method retrieves a list of events 
        /// from the database using Event, Vendor, and EventVendor Repositories. 
        /// </summary>
        /// <returns>IActionResult</returns>
        [Route("admin/eventvendors/list")]
        public ActionResult Index(int? eventId, int? vendorId, string msg, string err, string searchString)
        {
            EventVendorRepository evRepo = new EventVendorRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);

            var eventVendors = evRepo.GetAllEventVendors();


            // grab event vendors if event id or vendor id is not null
            if(eventId != null)
            {
                eventVendors = evRepo.GetEventVendorByEventId(eventId);
            }

            if (vendorId != null)
            {
                eventVendors = evRepo.GetEventVendorByVendorId(vendorId);
            }

            // assign all event and vendor for each EventVendor to be displayed in table in view
            foreach(var ev in eventVendors)
            {
                ev.Event = eventRepo.GetEventById(ev.EventId);
                ev.Vendor = vendorRepo.GetRecord(ev.VendorId);
            }

            // check if search string is empty,
            // if not empty, look for EventVendors in db where
            // properties contain search string
            if (!string.IsNullOrEmpty(searchString))
            {
                eventVendors = _foodScapeContext
                               .EventVendors
                               .Where(x =>
                                      x.EventVendorId.ToString().Contains(searchString) ||
                                      x.Vendor.Name.Contains(searchString) ||
                                      x.Event.Name.Contains(searchString)).ToList();
            }

            // switch value of msg and err into empty string if null
            if (msg == null)
            {
                msg = "";
            }

            if (err == null)
            {
                err = "";
            }

            // store err and msg in ViewBag to be displayed
            ViewBag.Message = msg;
            ViewBag.Error = err;
            return View(eventVendors);
        }

        // GET: EventVendorController/Details/5
        [Route("admin/eventvendors/details/{id}")]
        public ActionResult Details(int id)
        {
            EventVendorRepository evRepo = new EventVendorRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);

            var eventVendor = evRepo.GetEventVendorById(id);

            eventVendor.Event = eventRepo.GetEventById(eventVendor.EventId);
            eventVendor.Vendor = vendorRepo.GetRecord(eventVendor.VendorId);

            return View(eventVendor);
        }

        // GET: EventVendorController/Create
        [Route("admin/eventvendors/create")]
        public ActionResult Create()
        {
            EventRepository eventRepo = new EventRepository(_foodScapeContext);
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);

            var events = eventRepo.GetAllEvents().ToList();
            var vendors = vendorRepo.GetRecords().ToList();

            // make list of SelectListItems for events and vendors
            var preEventsDropDownList = events.Select(e =>
                new SelectListItem { Value = e.EventId.ToString(), Text = e.Name }
            ).ToList();
            var eventsDropDownList = new SelectList(preEventsDropDownList, "Value", "Text");

            var preVendorsDropDownList = vendors.Select(v =>
                new SelectListItem { Value = v.VendorId.ToString(), Text = v.Name }
            ).ToList();
            var vendorsDropDownList = new SelectList(preVendorsDropDownList, "Value", "Text");

            // store the dropdown lists in ViewBag to be displayed in view
            ViewBag.EventSelectList = eventsDropDownList;
            ViewBag.VendorSelectList = vendorsDropDownList;

            return View();
        }

        // POST: EventVendorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/eventvendors/create")]
        public ActionResult Create(EventVendor eventVendor)
        {
            EventVendorRepository evRepo = new EventVendorRepository(_foodScapeContext);
            try
            {
                evRepo.CreateEventVendor(eventVendor);
                return RedirectToAction("Index", new {msg = "Successfully created new Event Vendor!" });
            }
            catch
            {
                return RedirectToAction("Index", new {err = "Failed creating new Event Vendor."});
            }
        }

        // GET: EventVendorController/Edit/5
        [Route("admin/eventvendors/edit")]
        public ActionResult Edit(int id)
        {
            EventVendorRepository evRepo = new EventVendorRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);

            var eventVendor = evRepo.GetEventVendorById(id);

            var events = eventRepo.GetAllEvents().ToList();
            var vendors = vendorRepo.GetRecords().ToList();

            ViewBag.SelectedEvent = eventVendor.Event.Name;
            ViewBag.SelectedVendor = eventVendor.Vendor.Name;

            // make list of SelectListItems for events and vendors
            var preEventsDropDownList = events.Select(e =>
                new SelectListItem { Value = e.EventId.ToString(), Text = e.Name }
            ).ToList();
            var eventsDropDownList = new SelectList(preEventsDropDownList, "Value", "Text");

            var preVendorsDropDownList = vendors.Select(v =>
                new SelectListItem { Value = v.VendorId.ToString(), Text = v.Name }
            ).ToList();
            var vendorsDropDownList = new SelectList(preVendorsDropDownList, "Value", "Text");

            // store the dropdown lists in ViewBag to be displayed in view
            ViewBag.EventSelectList = eventsDropDownList;
            ViewBag.VendorSelectList = vendorsDropDownList;

            return View(eventVendor);
        }

        // POST: EventVendorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/eventvendors/edit")]
        public ActionResult Edit(EventVendor newEventVendor)
        {
            EventVendorRepository evRepo = new EventVendorRepository(_foodScapeContext);
            try
            {
                evRepo.EditEventVendor(newEventVendor);
                return RedirectToAction("Index", new { msg = "Successfully edited Event Vendor!" });
            }
            catch
            {
                return RedirectToAction("Index", new { err = "Failed editing Event Vendor." });
            }
        }

        // GET: EventVendorController/Delete/5
        [Route("admin/eventvendors/delete")]
        public ActionResult Delete(int id)
        {           
            EventVendorRepository evRepo = new EventVendorRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);

            var eventVendor = evRepo.GetEventVendorById(id);
            eventVendor.Event = eventRepo.GetEventById(eventVendor.EventId);
            eventVendor.Vendor = vendorRepo.GetRecord(eventVendor.VendorId);

            return View(eventVendor);
        }

        // POST: EventVendorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/eventvendors/delete")]
        public ActionResult Delete(EventVendor eventVendor)
        {
            EventVendorRepository evRepo = new EventVendorRepository(_foodScapeContext);
            var ev = evRepo.GetEventVendorById(eventVendor.EventVendorId);
            try
            {
                evRepo.DeleteEventVendor(ev);
                return RedirectToAction("Index", new { msg = "Successfully deleted Event Vendor!" });
            }
            catch
            {
                return RedirectToAction("Index", new { err = "Failed deleting Event Vendor." });
            }
        }
    }
}

Views/EventVendor/Create.cshtml
@model Food_Scape.Models.EventVendor

@{
    ViewData["Title"] = "Create";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-3 mx-auto">
        <h1 class="text-center">Create Event</h1>
        <hr />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                
                @Html.DropDownList(
                    "EventId",
                    new SelectList(ViewBag.EventSelectList, 
                        "Value",
                        "Text"
                    ),
                    "Select Event",
                    new { @id = "eventDD", @class = "form-control mb-3"}
                )

                <span asp-validation-for="EventId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendorId" class="control-label"></label>

                @Html.DropDownList(
                    "VendorId",
                    new SelectList(ViewBag.VendorSelectList, 
                        "Value",
                        "Text"
                    ),
                    "Select Vendor",
                    new { @id = "vendorDD", @class = "form-control mb-3"}
                )             
                
                <span asp-validation-for="VendorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index">Back to Event List</a>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/EventVendor/Delete.cshtml
@model Food_Scape.Models.EventVendor
@{
    ViewData["Title"] = "Delete";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-11 mx-auto">
        <h1 class="text-center">Delete Event Vendor</h1>
        <h3 class="text-center">Are you sure you want to delete this?</h3>
        <hr />
        <dl class="col-sm-3 row mx-auto">
            <dt class="col-sm-5">
                Event Vendor ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.EventVendorId)
            </dd>
            <dt class="col-sm-5">
                Event ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.EventId)
            </dd>
            <dt class="col-sm-5">
                Event Name
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Event.Name)
            </dd>
            <dt class="col-sm-5">
                Vendor ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.VendorId)
            </dd>
            <dt class="col-sm-5">
                Vendor Name
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Vendor.Name)
            </dd>

        </dl>

        <form asp-action="Delete">
            <div class="col-sm-3 mx-auto d-flex flex-column justify-content-evenly align-items-center">
                <input type="hidden" asp-for="EventVendorId" />
                <input type="submit" value="Delete" class="btn btn-danger mb-3" />
                <a asp-action="Index">Back to Event List</a>
            </div>
        </form>
    </div>
</div>

Views/EventVendor/Details.cshtml
@model Food_Scape.Models.EventVendor

@{
    ViewData["Title"] = "Details";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-11 mx-auto">
        <h1 class="text-center">Event Vendor Details</h1>
        <hr />
        <dl class="col-sm-3 row mx-auto">
            <dt class="col-sm-5">
                Event Vendor ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.EventVendorId)
            </dd>
            <dt class="col-sm-5">
                Event ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.EventId)
            </dd>
            <dt class="col-sm-5">
                Event Name
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Event.Name)
            </dd>
            <dt class="col-sm-5">
                Vendor ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.VendorId)
            </dd>
            <dt class="col-sm-5">
                Vendor Name
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Vendor.Name)
            </dd>

        </dl>
        <div class="col-sm-3 mx-auto d-flex justify-content-between">
            <a asp-action="Edit" asp-route-id="@Model?.VendorId">Edit</a>
            <div class="d-flex flex-column">
                <a asp-action="Index">Back to Event Vendor List</a>
            </div>
        </div>
    </div>
</div>

Views/EventVendor/Edit.cshtml
@model Food_Scape.Models.EventVendor
@{
    ViewData["Title"] = "Edit";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-4 mx-auto">
        <h1 class="text-center">Edit Event Vendor</h1>
        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventVendorId" class="control-label"></label>
                <input asp-for="EventVendorId" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                @Html.DropDownList(
                    "EventId",
                    new SelectList(ViewBag.EventSelectList, 
                        "Value",
                        "Text",
                        ViewBag.SelectedEvent
                    ),
                    "Select Event",
                    new { @id = "eventDD", @class = "form-control mb-3"}
                )
                <span asp-validation-for="EventId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendorId" class="control-label"></label>
                @Html.DropDownList(
                    "VendorId",
                    new SelectList(ViewBag.VendorSelectList, 
                        "Value",
                        "Text",
                        ViewBag.SelectedVendor
                    ),
                    "Select Vendor",
                    new { @id = "vendorDD", @class = "form-control mb-3"}
                ) 
                <span asp-validation-for="VendorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index">Back to Event Vendor List</a>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/EventVendor/Index.cshtml
@model IEnumerable<Food_Scape.Models.EventVendor>
@{
    ViewData["Title"] = "Index";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-sm-9 mx-auto">
        @if (ViewBag.Message != "")
        {
            <h1 class="text-success text-center">@ViewBag.Message</h1>
        }
        @if (ViewBag.Error != "")
        {
            <h1 class="text-danger text-center">@ViewBag.Error</h1>
        }
        <h1 class="text-center">Event Vendors</h1>
        <p class="text-center">
            <a asp-action="Create" asp-controller="EventVendor">Create New Event Vendor</a>
        </p>
        <form asp-action="Index" method="get" class="px-5">
            <div class="form-actions no-color admin-searchBar d-flex flex-row justify-content-center align-items-center">
                <div class="form-group align-items-center" style="display: inline-block">
                    <span>Search Event Vendors:</span>
                    <input type="text" name="SearchString"
                           value="@ViewData["currentFilter"]" required />
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
                <a asp-action="Index" class="mx-4">Clear Search Bar</a>
            </div>
        </form>

        <div class="admin-panel overflow-auto">
            <table class="table table-bordered text-center table-striped shadow rounded">
                <thead>
                    <tr>
                        <th>Event Vendor ID</th>
                        <th>Event ID</th>
                        <th>Event</th>
                        <th>Vendor ID</th>
                        <th>Vendor</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var eventVendor in Model)
                    {
                        <tr>
                            <td>@eventVendor.EventVendorId</td>
                            <td>@eventVendor.EventId</td>
                            <td>@eventVendor.Event.Name</td>
                            <td>@eventVendor.VendorId</td>
                            <td>@eventVendor.Vendor.Name</td>
                            <td>
                                <a asp-action="Edit" asp-controller="EventVendor" asp-route-id="@eventVendor.EventVendorId">Edit</a> |
                                <a asp-action="Details" asp-controller="EventVendor" asp-route-id="@eventVendor.EventVendorId">Details</a> |
                                <a asp-action="Delete" asp-controller="EventVendor" asp-route-id="@eventVendor.EventVendorId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="h4">
            <a asp-action="Index" asp-controller="Admin">Back to Admin Panel</a>
        </div>
    </div>
</div>