Models/Vendor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Food_Scape.Models;

public partial class Vendor
{
    public int VendorId { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string? VendorType { get; set; }

    public string? Location { get; set; }

    public string? ImageUrl { get; set; }

    public virtual ICollection<EventVendor> EventVendors { get; } = new List<EventVendor>();
}

Controllers/VendorController.cs
using Food_Scape.Models;
using Food_Scape.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Food_Scape.Controllers
{
    public class VendorController : Controller
    {
        FoodScapeContext _foodScapeContext;

        public VendorController(FoodScapeContext foodScapeContext)
        {
            _foodScapeContext = foodScapeContext;
        }

        //Method to send the vendors information to the view.
        [Route("/vendors")]
        public IActionResult Index(string searchString)
        {
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
            var vendors = vendorRepo.GetRecordsVM();

            if (!string.IsNullOrEmpty(searchString))
            {
                vendors = vendorRepo.GetRecordsByTypeVM(searchString);
            }

            return View(vendors);
        }

        //Method to get the list of vendors in the admin panel.
        [Route("admin/vendor/list")]
        [Authorize(Roles = "Admin")]
        public IActionResult AdminIndex(string msg, string err, string searchString)
        {
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
            var vendors = vendorRepo.GetRecordsList();

            if(!string.IsNullOrEmpty(searchString))
            {
                vendors = _foodScapeContext.Vendors
                          .Where(x => 
                            x.VendorId.ToString().Contains(searchString) || 
                            x.Name.Contains(searchString) ||
                            x.Description.Contains(searchString) ||
                            x.VendorType.Contains(searchString) ||
                            x.Location.Contains(searchString)).ToList();
            }

            if (msg == null)
            {
                msg = "";
            }

            if (err == null)
            {
                err = "";
            }

            return View(vendors);
        }

        //Method to pass the detail of a vendor to the Details View.
        [Route("admin/vendor/details/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Details(int id)
        {
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
            Vendor vendor = vendorRepo.GetRecord(id);

            return View(vendor);
        }

        //Method to display the view to create a new vendor.
        [Route("admin/vendor/create")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        //Method to create a new vendor.
        [Route("admin/vendor/create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
                    vendorRepo.CreateRecord(vendor);
                    return RedirectToAction("AdminIndex", new { msg = "Successfully created Vendor!" });
                }
                catch
                {
                    return RedirectToAction("AdminIndex", new { err = "Failed creating Vendor!" });
                }
            }

            return View(vendor);
        }

        //Method to display the view to edit an existing vendor.
        [Route("admin/vendor/edit")]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
            Vendor vendor = vendorRepo.GetRecord(id);

            return View(vendor);
        }

        //Method to edit an existing vendor.
        [Route("admin/vendor/edit")]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
                    vendorRepo.EditRecord(vendor);
                    return RedirectToAction("AdminIndex", new { msg = "Successfully edited Vendor!" });
                }
                catch 
                {
                    return RedirectToAction("AdminIndex", new { err = "Failed editing Vendor!" });
                }
            }

            return View(vendor);
        }

        //Vendor to display the view to delete a vendor.
        [Route("admin/vendor/delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
            Vendor vendor = vendorRepo.GetRecord(id);

            return View(vendor);
        }

        //Method to delete a vendor.
        [Route("admin/vendor/delete")]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    VendorRepository vendorRepo = new VendorRepository(_foodScapeContext);
                    vendorRepo.DeleteRecord(vendor);
                    return RedirectToAction("AdminIndex", new { msg = "Successfully deleted Vendor!" });
                }
                catch
                {
                    return RedirectToAction("AdminIndex", new { err = "Failed deleting Vendor!" });
                }
            }

            return View(vendor);
        }
    }
}

Views/Vendor/AdminIndex.cshtml
@model IEnumerable<Food_Scape.Models.Vendor>
@{
    ViewData["Title"] = "AdminIndex";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-6 mx-auto">
        @if (ViewBag.Message != "")
        {
            <h1 class="text-success text-center">@ViewBag.Message</h1>
        }
        @if (ViewBag.Error != "")
        {
            <h1 class="text-danger text-center">@ViewBag.Error</h1>
        }
        <h1 class="text-center">Vendors</h1>
        <p class="text-center">
            <a asp-action="Create" asp-controller="Vendor">Create New Vendor</a>
        </p>
        <form asp-action="AdminIndex" method="get" class="px-5">
            <div class="form-actions no-color admin-searchBar d-flex flex-row justify-content-center align-items-center">
                <div class="form-group align-items-center" style="display: inline-block">
                    <span>Search Vendors:</span>
                    <input type="text" name="SearchString"
                           value="@ViewData["currentFilter"]" required />
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
                <a asp-action="AdminIndex" class="mx-4">Clear Search Bar</a>
            </div>
        </form>

        <div class="admin-panel overflow-auto">
            <table class="table table-bordered text-center table-striped shadow rounded">
                <thead>
                    <tr>
                        <th>Vendor ID</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Location</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var vendor in Model)
                    {
                        <tr>
                            <td>@vendor.VendorId</td>
                            <td>@vendor.Name</td>
                            <td>@vendor.VendorType</td>
                            <td>@vendor.Location</td>
                            <td>
                                <a asp-action="Edit" asp-controller="Vendor" asp-route-id="@vendor.VendorId">Edit</a> |
                                <a asp-action="Details" asp-controller="Vendor" asp-route-id="@vendor.VendorId">Details</a> |
                                <a asp-action="Delete" asp-controller="Vendor" asp-route-id="@vendor.VendorId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="h4">
        <a asp-action="Index" asp-controller="Admin">Back to Admin Panel</a>
        </div>
    </div>
</div>

Views/Vendor/Create.cshtml
@model Food_Scape.Models.Vendor

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-3 mx-auto">
        <h1 class="text-center">Create Vendor</h1>
        <hr />
        <form asp-action="Create">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input type="date" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input type="date" asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendorType" class="control-label"></label>
                <select asp-for="VendorType" class="form-control">
                    <option value="Beverages">Beverages</option>
                    <option value="Food">Food</option>
                    <option value="Activity">Activity</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="AdminIndex">Back to Vendor List</a>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Vendor/Delete.cshtml
@model Food_Scape.Models.Vendor

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-11 mx-auto">
        <h1 class="text-center">Delete Vendor</h1>
        <h3 class="text-center">Are you sure you want to delete this?</h3>

        <hr />
        <dl class="col-sm-3 row mx-auto">
            <dt class="col-sm-5">
                Vendor
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-5">
                Description
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-5">
                From
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt class="col-sm-5">
                To
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.EndDate)
            </dd>
            <dt class="col-sm-5">
                Type
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.VendorType)
            </dd>
            <dt class="col-sm-5">
                Location
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Location)
            </dd>
        </dl>

        <form asp-action="Delete">
            <div class="col-sm-3 mx-auto d-flex flex-column justify-content-evenly align-items-center">
                <input type="hidden" asp-for="VendorId" />
                <input type="submit" value="Delete" class="btn btn-danger mb-3" />
                <a asp-action="AdminIndex">Back to Vendor List</a>
            </div>
        </form>
    </div>
</div>

Views/Vendor/Details.cshtml
@model Food_Scape.Models.Vendor

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="h-100 d-flex align-items-center">
    <div class="col-11 mx-auto">
        <h1 class="text-center">Vendor Details</h1>
        <hr />
        <div style="height: 300px;" class="d-flex justify-content-center align-items-center mb-3">
            <img class="mx-auto" src="@Model.ImageUrl" alt="@Model.Name" style="max-height: 100%;"/>
        </div>
        <dl class="col-sm-3 row mx-auto">
            <dt class = "col-sm-5">
                Vendor
            </dt>
            <dd class = "col-sm-7">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class = "col-sm-5">
                Description
            </dt>
            <dd class = "col-sm-7">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class = "col-sm-5">
                From
            </dt>
            <dd class = "col-sm-7">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
            <dt class = "col-sm-5">
                To
            </dt>
            <dd class = "col-sm-7">
                @Html.DisplayFor(model => model.EndDate)
            </dd>
            <dt class = "col-sm-5">
                Type
            </dt>
            <dd class = "col-sm-7">
                @Html.DisplayFor(model => model.VendorType)
            </dd>
            <dt class = "col-sm-5">
                Location
            </dt>
            <dd class = "col-sm-7">
                @Html.DisplayFor(model => model.Location)
            </dd>
        </dl>
        <div class="col-sm-3 mx-auto d-flex justify-content-between">
            <a asp-action="Edit" asp-route-id="@Model?.VendorId">Edit</a>
            <div class="d-flex flex-column">
                <a asp-action="AdminIndex">Back to Admin Vendor List</a>
            </div>
        </div>
    </div>
</div>

Views/Vendor/Edit.cshtml
@model Food_Scape.Models.Vendor

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="h-100 d-flex align-items-center">
    <div class="col-4 mx-auto">
        <h1 class="text-center">Edit Vendor</h1>
        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VendorId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input type="date" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input type="date" asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendorType" class="control-label"></label>
                <select asp-for="VendorType" class="form-control">
                    <option value="Beverages">Beverages</option>
                    <option value="Food">Food</option>
                    <option value="Activity">Activity</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="AdminIndex">Back to Vendor List</a>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Vendor/Index.cshtml
@model IEnumerable<Food_Scape.ViewModels.VendorVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid p-0" style="margin-bottom: 25px;">

    <div class="row no-gutters">
        <div class="col-md-12">
            <img src="~/images/banners/Vendors.png" alt="Banner Image" class="w-100">
        </div>
    </div>
</div>

<!--Vendor Filters-->
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 text-center">
    <form asp-action="Index" method="get" class="px-5">
        <input type="submit" value="All" class="btn btn-dark" style="width: 200px" />
    </form>
    <form asp-action="Index" method="get" class="px-5">
        <input type="hidden" name="SearchString" value="Food" />
        <input type="submit" value="Food" class="btn btn-dark" style="width: 200px" />
    </form>
    <form asp-action="Index" method="get" class="px-5">
        <input type="hidden" name="SearchString" value="Beverages"/>
        <input type="submit" value="Beverages" class="btn btn-dark" style="width: 200px" />
    </form>
    <form asp-action="Index" method="get" class="px-5">
        <input type="hidden" name="SearchString" value="Activity" />
        <input type="submit" value="Activity" class="btn btn-dark" style="width: 200px" />
    </form>
</div>

<!--List of vendors-->
@if (Model != null && Model.Any())
{
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 justify-content-center">
        @foreach (var vendor in Model)
        {
            <div class="card" style="max-width: 400px; margin: 10px;">
                <div class="card-img-top" style="height: 200px; overflow: hidden; text-align: center; padding-top: 15px;">
                    <img src="@vendor.Vendor.ImageUrl" alt="@vendor.Vendor.Name" style="object-fit: cover; max-height: 100%; max-width: 100%; border-radius: 100%; box-shadow: 7px 0 5px lightgray;">
                </div>
                <div class="card-body">
                    <h5 class="card-title">@vendor.Vendor.Name</h5>
                    <p class="card-text">Description: @vendor.Vendor.Description</p>
                    <p class="card-text">Type: @vendor.Vendor.VendorType</p>
                    <span class="card-text">Events: </span>
                    @{
                        var i=0;
                        var count = vendor.Events.Count();
                    }
                    @foreach(var ev in vendor.Events)
                    {
                        @if (++i == count)
                        {
                            <span class="card-text">@ev.Name</span>
                        } 
                        else
                        {
                            <span class="card-text">@ev.Name | </span>
                        }
                    }
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="text-center">
        <p>No vendors found</p>
    </div>
}