Controllers/TicketTypeController.cs
using Food_Scape.Models;
using Food_Scape.Repositories;
using Food_Scape.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Logging;

namespace Food_Scape.Controllers
{
    public class TicketTypeController : Controller
    {
        FoodScapeContext _foodScapeContext;

        public TicketTypeController(FoodScapeContext foodScapeContext)
        {
            _foodScapeContext = foodScapeContext;
        }

        /// <summary>
        /// The method retrieves a list of ticket types and corresponding events 
        /// from the database using TicketTypeRepository and EventRepository. 
        /// </summary>
        /// <returns>IActionResult</returns>

        [Route("tickets")]

        public IActionResult Index()
        {
            TicketTypeRepository ticketTypeRepository = new TicketTypeRepository(_foodScapeContext);
            var ticketType = ticketTypeRepository.GetAllTicketTypes().ToList();

            EventRepository eRepo = new EventRepository(_foodScapeContext);
            var events = eRepo.GetAllEvents();

            List<TicketTypeVM> ticketVM = new List<TicketTypeVM>();
            foreach (var ticket in ticketType)
            {
                var eventName = events.FirstOrDefault(ev => ev.EventId == ticket.EventId)?.Name;
                var startDate = events.FirstOrDefault(ev => ev.EventId == ticket.EventId)?.StartDate;
                string strDate = startDate.ToString();
                var endDate = events.FirstOrDefault(ev => ev.EventId == ticket.EventId)?.EndDate;
                string enDate = endDate.ToString();

                var location = events.FirstOrDefault(ev => ev.EventId == ticket.EventId)?.Address;
                var about = events.FirstOrDefault(ev => ev.EventId == ticket.EventId)?.Description;
                TicketTypeVM tempTicket = new TicketTypeVM
                {
                    TicketTypeId = ticket.TicketTypeId,
                    EventId = ticket.EventId,
                    TicketType1 = ticket.TicketType1,
                    Price = ticket.Price,
                    Discount = ticket.Discount,
                    Name = eventName,
                    StartDate = strDate.Substring(0,10),
                    EndDate= enDate.Substring(0,10),
                    Address= location,
                    Description = about,
                };
                ticketVM.Add(tempTicket);

            }
            return View(ticketVM);
        }

        /// <summary>
        /// Tickets Admin Pages / CRUD
        /// 
        /// The method retrieves a list of TicketTypes 
        /// from the database using TicketType Repository. 
        /// </summary>
        /// <returns>IActionResult</returns>
        [Route("admin/tickettypes/list")]
        [Authorize(Roles = "Admin")]
        public IActionResult AdminIndex(string msg, string err, string searchString)
        {
            TicketTypeRepository ticketTypeRepo = new TicketTypeRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);

            var ticketTypes = ticketTypeRepo.GetAllTicketTypes();

            // check if search string is empty,
            // if not empty, look for TicketTypes in db where
            // properties contain search string
            if (!string.IsNullOrEmpty(searchString))
            {
                ticketTypes = _foodScapeContext
                                .TicketTypes
                                .Where(x => 
                                    x.TicketTypeId.ToString().Contains(searchString) ||
                                    x.TicketType1.Contains(searchString) ||
                                    x.Price.ToString().Contains(searchString) ||
                                    x.Discount.ToString().Contains(searchString) ||
                                    x.Day.ToString().Contains(searchString) || 
                                    x.Event.Name.Contains(searchString)).ToList();
            }

            // switch value of msg and err into empty string if null
            if (msg == null)
            {
                msg = "";
            }

            if (err == null)
            {
                err = "";
            }

            // attach event for each ticketType
            foreach (var ticket in ticketTypes)
            {
                ticket.Event = eventRepo.GetEventById(ticket.EventId);
            }

            // store err and msg in ViewBag to be displayed
            ViewBag.Message = msg;
            ViewBag.Error = err;

            return View(ticketTypes);
        }

        [Route("admin/tickettypes/details/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Details(int id)
        {
            TicketTypeRepository ticketTypeRepository = new TicketTypeRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);

            TicketType ticketType = ticketTypeRepository.GetTicketType(id);
            ticketType.Event = eventRepo.GetEventById(ticketType.EventId);

            return View(ticketType);
        }

        [Route("admin/tickettypes/create")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            EventRepository eventRepo = new EventRepository(_foodScapeContext);
            var events = eventRepo.GetAllEvents().ToList();

            // make list of SelectListItems for events
            var preEventsDropDownList = events.Select(e =>
                new SelectListItem { Value = e.EventId.ToString(), Text = e.Name }
            ).ToList();
            var eventsDropDownList = new SelectList(preEventsDropDownList, "Value", "Text");

            ViewBag.EventSelectList = eventsDropDownList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/tickettypes/create")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(TicketType ticketType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TicketTypeRepository ticketTypeRepository = new TicketTypeRepository(_foodScapeContext);
                    ticketTypeRepository.CreateTicketType(ticketType);
                    return RedirectToAction("AdminIndex", new { msg = "Succesfully created new Ticket Type!" });
                }
                catch
                {
                    return RedirectToAction("AdminIndex", new { err = "Failed creating new Ticket Type." });
                }
            }
            return View();
        }

        [Route("admin/tickettypes/edit")]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            TicketTypeRepository ticketTypeRepository = new TicketTypeRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);

            TicketType ticketType = ticketTypeRepository.GetTicketType(id);
            ticketType.Event = eventRepo.GetEventById(ticketType.EventId);

            // store event name from attached event from ticket type in view bag
            if(ticketType.Event != null)
            {
                ViewBag.SelectedEvent = ticketType.Event.Name;
            }
            else
            {
                ViewBag.SelectedEvent = "";
            }

            // make the dropdown for all events
            var events = eventRepo.GetAllEvents().ToList();
            var preEventsDropDownList = events.Select(e =>
                new SelectListItem { Value = e.EventId.ToString(), Text = e.Name }
            ).ToList();
            var eventsDropDownList = new SelectList(preEventsDropDownList, "Value", "Text");

            ViewBag.EventSelectList = eventsDropDownList;

            return View(ticketType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/tickettypes/edit")]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(TicketType ticketType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TicketTypeRepository ticketTypeRepository = new TicketTypeRepository(_foodScapeContext);
                    ticketTypeRepository.EditTicketType(ticketType);
                    return RedirectToAction("AdminIndex", new { msg = "Succesfully Edited Ticket Type!" });
                }
                catch
                {
                    return RedirectToAction("AdminIndex", new { err = "Failed editing Ticket Type." });
                }
            }

            return View(ticketType);
        }

        [Route("admin/tickettypes/delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            TicketTypeRepository ticketTypeRepository = new TicketTypeRepository(_foodScapeContext);
            EventRepository eventRepo = new EventRepository(_foodScapeContext);

            TicketType ticketType = ticketTypeRepository.GetTicketType(id);
            ticketType.Event = eventRepo.GetEventById(ticketType.EventId);

            return View(ticketType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("admin/tickettypes/delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(TicketType ticketType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TicketTypeRepository ticketTypeRepository = new TicketTypeRepository(_foodScapeContext);
                    ticketTypeRepository.DeleteTicketType(ticketType);
                    return RedirectToAction("AdminIndex", new { msg = "Succesfully deleted Ticket Type!" });
                }
                catch
                {

Views/TicketType/AdminIndex.cshtml
@model IEnumerable<Food_Scape.Models.TicketType>

@{
    ViewData["Title"] = "AdminIndex";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-11 mx-auto">
        @if (ViewBag.Message != "")
        {
            <h1 class="text-success text-center">@ViewBag.Message</h1>
        }
        @if (ViewBag.Error != "")
        {
            <h1 class="text-danger text-center">@ViewBag.Error</h1>
        }
        <h1 class="text-center">Ticket Types</h1>
        <p class="text-center">
            <a asp-action="Create" asp-controller="TicketType">Create New Ticket Type</a>
        </p>
        <form asp-action="AdminIndex" method="get" class="px-5">
            <div class="form-actions no-color admin-searchBar d-flex flex-row justify-content-center align-items-center">
                <div class="form-group align-items-center" style="display: inline-block">
                    <span>Search Vendors:</span>
                    <input type="text" name="SearchString"
                           value="@ViewData["currentFilter"]" required />
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
                <a asp-action="AdminIndex" class="mx-4">Clear Search Bar</a>
            </div>
        </form>

        <div class="admin-panel overflow-auto">
            <table class="table table-bordered text-center table-striped shadow rounded">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Ticket Type</th>
                        <th>Price</th>
                        <th>Discount</th>
                        <th>Day</th>
                        <th>Event</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var ticketType in Model)
                    {
                        <tr>
                            <td>@ticketType.TicketTypeId</td>
                            <td>@ticketType.TicketType1</td>
                            <td>@ticketType.Price</td>
                            <td>@ticketType.Discount</td>
                            <td>@ticketType.Day</td>
                            @if (ticketType.Event != null)
                            {
                                <td>@ticketType.Event.Name</td>
                            } 
                            else
                            {
                                <td></td>
                            }
                            <td>
                                <a asp-action="Edit" asp-controller="TicketType" asp-route-id="@ticketType.TicketTypeId">Edit</a> |
                                <a asp-action="Details" asp-controller="TicketType" asp-route-id="@ticketType.TicketTypeId">Details</a> |
                                <a asp-action="Delete" asp-controller="TicketType" asp-route-id="@ticketType.TicketTypeId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="h4">
            <a asp-action="Index" asp-controller="Admin">Back to Admin Panel</a>
        </div>
    </div>
</div>

Views/TicketType/Create.cshtml
@model Food_Scape.Models.TicketType

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-3 mx-auto">
        <h1 class="text-center">Create Event</h1>
        <hr />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TicketType1" class="control-label"></label>
                <input asp-for="TicketType1" class="form-control" />
                <span asp-validation-for="TicketType1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                @Html.DropDownList(
                    "EventId",
                    new SelectList(ViewBag.EventSelectList, 
                        "Value",
                        "Text"
                    ),
                    "Select Event",
                    new { @id = "eventDD", @class = "form-control mb-3"}
                )
                <span asp-validation-for="EventId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="AdminIndex">Back to Ticket Type List</a>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TicketType/Delete.cshtml
@model Food_Scape.Models.TicketType

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="h-100 d-flex align-items-center">
    <div class="col-11 mx-auto">
        <h1 class="text-center">Delete Ticket Type</h1>
        <h3 class="text-center">Are you sure you want to delete this?</h3>

        <hr />
        <dl class="col-sm-3 row mx-auto">
            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.TicketTypeId)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.TicketTypeId)
            </dd>
            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.TicketType1)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.TicketType1)
            </dd>
            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.Discount)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Discount)
            </dd>
            <dt class="col-sm-5">
                @Html.DisplayNameFor(model => model.Day)
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Day)
            </dd>
            <dt class="col-sm-5">
                Event Name
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Event.Name)
            </dd>
        </dl>

        <form asp-action="Delete">
            <div class="col-sm-3 mx-auto d-flex flex-column justify-content-evenly align-items-center">

                <input type="hidden" asp-for="TicketTypeId" />
                <input type="submit" value="Delete" class="btn btn-danger mb-3" /> 
                <a asp-action="AdminIndex">Back to List</a>
            </div>
        </form>
    </div>
</div>

Views/TicketType/Details.cshtml
@model Food_Scape.Models.TicketType

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-11 mx-auto">
        <h1 class="text-center">Ticket Type Details</h1>
        <hr />
        <dl class="col-sm-3 row mx-auto">
            <dt class="col-sm-5">
                Ticket Type ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.TicketTypeId)
            </dd>
            <dt class="col-sm-5">
                Ticket Type
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.TicketType1)
            </dd>
            <dt class="col-sm-5">
                Price
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-5">
                Discount
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Discount)
            </dd>
            <dt class="col-sm-5">
                Day
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Day)
            </dd>
            <dt class="col-sm-5">
                Event ID
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.EventId)
            </dd>
            <dt class="col-sm-5">
                Event Name
            </dt>
            <dd class="col-sm-7">
                @Html.DisplayFor(model => model.Event.Name)
            </dd>

        </dl>
        <div class="col-sm-3 mx-auto d-flex justify-content-between">
            <a asp-action="Edit" asp-route-id="@Model?.TicketTypeId">Edit</a>
            <div class="d-flex flex-column">
                <a asp-action="AdminIndex">Back to Ticket Type List</a>
            </div>
        </div>
    </div>
</div>

Views/TicketType/Edit.cshtml
@model Food_Scape.Models.TicketType

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="h-100 d-flex align-items-center">
    <div class="col-3 mx-auto">
        <h1 class="text-center">Create Event</h1>
        <hr />
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TicketTypeId" class="control-label"></label>
                <input asp-for="TicketTypeId" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="TicketType1" class="control-label"></label>
                <input asp-for="TicketType1" class="form-control" />
                <span asp-validation-for="TicketType1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                @Html.DropDownList(
                    "EventId",
                    new SelectList(ViewBag.EventSelectList,
                        "Value",
                        "Text"
                    ),
                    "Select Event",
                    new { @id = "eventDD", @class = "form-control mb-3" }
                )
                <span asp-validation-for="EventId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="AdminIndex">Back to Ticket Type List</a>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}